[package]
name = "atomic-arc"
version = "0.1.0"
authors = ["Andrew Cann <shum@canndrew.org>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ihciah/atomic-arc"
description = "Atomic arc"
keywords = ["atomic"]


[dependencies]
